version: '3.1'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
   container_name: elasticsearch
   ports:
    - "9200:9200"
   expose:
    - "9200"
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   networks:
    - docker-network

  kibana:
   image: docker.elastic.co/kibana/kibana:7.0.0
   container_name: kibana
   ports:
    - "5601:5601"
   expose:
    - "5601"
   environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - ELASTICSEARCH_USERNAME=elastic
    - ELASTIC_PWD=changeme
   links:
    - elasticsearch
   depends_on:
    - elasticsearch
   networks:
    - docker-network
  
networks:
  docker-network:

volumes:
  elasticsearch-data: